export enum Role {
  ADMIN = 'ADMIN',
  PROJECT_OWNER = 'PROJECT_OWNER',
  SCIENTIFIC_COMMITTEE = 'SCIENTIFIC_COMMITTEE',
  STAGE_SERVICE = 'STAGE_SERVICE',
  JURY_MEMBER = 'JURY_MEMBER',
  MEMBER = 'MEMBER',
  STARTUP_OWNER = 'STARTUP_OWNER',
}
